INSERT INTO ANALYSIS.TMP_RFM_MONETARY_VALUE
SELECT 
    USERS.USER_ID
    ,NTILE(5) OVER(ORDER BY COST_ALL) AS MONETARY_VALUE
FROM (
    WITH ORDERS AS
    (
    SELECT
        USER_ID
        ,SUM(COST) AS COST_ALL
    FROM ANALYSIS.ORDERS 
    WHERE STATUS = 4 AND CAST(ORDER_TS AS DATE) >=  '2022-01-01'::DATE
    GROUP BY 1
    )
    SELECT
        U.ID AS USER_ID
        ,COALESCE(COST_ALL, 0) AS COST_ALL
    FROM ANALYSIS.USERS U
    LEFT JOIN ORDERS O ON U.ID = O.USER_ID
    ) USERS;