INSERT INTO ANALYSIS.TMP_RFM_RECENCY
SELECT 
    USERS.USER_ID
    ,NTILE(5) OVER(ORDER BY DELTA DESC) AS RECENCY
FROM (
    WITH ORDERS AS
    (
    SELECT
        USER_ID
        ,CURRENT_DATE - CAST(MAX(ORDER_TS) AS DATE) AS DELTA
    FROM ANALYSIS.ORDERS O 
    WHERE STATUS = 4 AND CAST(ORDER_TS AS DATE) >= '2022-01-01' ::DATE
    GROUP BY 1
    )
    SELECT
        U.ID AS USER_ID
        ,COALESCE(DELTA, (SELECT MAX(DELTA) FROM ORDERS)) AS DELTA
    FROM ANALYSIS.USERS U
    LEFT JOIN ORDERS O ON U.ID = O.USER_ID
    ) USERS
;